version: "3.8"

volumes:
  db-volume:

networks:
  express:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    networks:
      - express
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    volumes:
      - ./src:/app:cached
    networks:
      - express
